# This is a basic workflow to help you get started with Actions

name: Build Validation

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install python3 python3-pip python3-setuptools python3-dev python3-wheel ninja-build gcc-10 g++-10

      - name: Install Meson
        run: sudo -H pip3 install meson

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Build
        run: CC=gcc-10 CXX=g++-10 meson build/ && ninja -C build/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: janus-ftl-orchestrator
          path: |
            build/janus-ftl-orchestrator
            build/janus-ftl-orchestrator-test
          if-no-files-found: error

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: janus-ftl-orchestrator

      - name: Run Tests
        run: ./janus-ftl-orchestrator-test